### ISSUE TITLE
Steps to include custom dependency in sample

### ISSUE THREAD

**Issue by PawelStadnicki** [fable-compiler/repl#102]
In docs there is description how to add own samples.
However I struggle to add a sample that uses my domain code from other assembly (and I want to keep it there)
If I put "open mydomain.subdomain" in my sample in REPL it cannot be compiled (the namespace or module is not defined). I added my dll (with .txt extension as well) to metadata folder.

I tried by adding my domain code via paket or nuget and I can see it is compiled to js but I still cannot compile the samples in Repl. 
Is there additional file to configure the mapping or any additional step? 
I tried to look at similar sample with Recharts but I do not understand the workflow of adding such a dependencies.

**Comment by alfonsogarciacaro** [comment]
Well, unfortunately this is a somewhat complicated process. Dependencies in the REPL are precompiled for better performance, but this is causes problems with Fable (inlined code, namespace resolution) so we used several hacks to make it work for this particular case.

Again, this was implemented in a quick and dirty way and it was not designed to be used general. But I think you can add extra dependencies following these steps:

- Bring in the dependency **sources** with Paket. The dependency shouldn't have public inlined functions.
- Add references to the dependency sources in [this project file](https://github.com/fable-compiler/repl/blob/master/src/Lib/Fable.Repl.Lib.fsproj). 
- Add an entry to this [JSON file](https://github.com/fable-compiler/repl/blob/master/public/repl-lib-map.json) to help Fable with the namespace resolution. An entry like this: `"Elmish.Program": ["Elmish", "src/program"]` means "to get a reference to a member of the Elmish.Program namespace, remove the Elmish- part and go to the src/program file (in the lib output folder)".
- Build the project to rebuild the library. You will likely have to check the `public/js/repl/lib` to see the exact path of the newly compiled sources.

**Comment by PawelStadnicki** [comment]
Thanks Alfonso.
So I was almost there but even with your suggestion I still cannot see my domain.
In paket I specify my github repository, my 2 files are downloaded and after adding to Repl Lib project they are successfully compiled and the lib folder is as follow:
![image](https://user-images.githubusercontent.com/56049414/71481754-6d2c8780-27ff-11ea-8297-7dad0fe57209.png)

wrometr.domain has two js files: Address.js and District.js
Repl-lib-map after modification contains following entry:
"wrometr.domain.addresses":["wrometr.domain.addresses", "wrometr.domain/Address"]

I'm compailing the repl.lib project and copying the dll (dll.txt) to metadata folder
Still cannot find the domain in Repl:
![image](https://user-images.githubusercontent.com/56049414/71482117-36f00780-2801-11ea-974c-33384acd7f55.png)

**Comment by PawelStadnicki** [comment]
well, it worked with yet another building, strange but maybe common.
I'm playing now with typical bindings like simple-statistics, turfjs, D3js.
If no further problems I will close the issue and maybe do the PR, do you welcome such a samples?
