### ISSUE TITLE
 List.chunkBySize doesn't work

### ISSUE THREAD

**Issue by Aoi-Erimiya** [fable-compiler/repl#105]
List.chunkBySize is doesn't work.

Oddly, printfn "start" and printfn "end" also do not work.

```fsharp
let list1 = [ 1 .. 10 ]

printfn "start"
printfn "%A" (List.chunkBySize 2 list1)
printfn "end"
```

**Comment by MangelMaxime** [comment]
We need to publish a new version of the REPL.

`List.chunckBySize` has been added to Fable the [31 Oct 2019](https://github.com/fable-compiler/Fable/commit/218dca5ce4aa5230ffa31e2d59adca48b15b59c9) but the latest REPL version if from `30 Sep 2019`

**Comment by Aoi-Erimiya** [comment]
Thank you.
Wait for the latest version to be released.

**Comment by MangelMaxime** [comment]
A new version of the REPL has been published, you can now use `List.chunkBySize` in it

**Comment by Aoi-Erimiya** [comment]
@MangelMaxime 
Wonderful!
Thank you for teaching me!
