### ISSUE TITLE
Elmish -> simple input example

### ISSUE THREAD

**Issue by MarcinGajda36** [fable-compiler/repl#106]
There is error in update method in samples -> Elmish -> simple input
currently there is:

```fs
let update (msg:Msg) (model:Model) =
    match msg with
    | ChangeValue newValue ->
        { Value = newValue }, Cmd.none
```

but it should be:

```fs
let update (msg:Msg) (model:Model) =
    match msg with
    | ChangeValue newValue ->
        { model with Value = newValue }, Cmd.none
```
Your current update method is not updating but creating completely new Model.
If that is intentional you should not take (model:Model) as argument.

**Comment by MangelMaxime** [comment]
This is indeed an error
