### ISSUE TITLE
REPL is broken

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/repl#119]
@alfonsogarciacaro  First congrats on the release of Fable 3.

I think the new release of the REPL broke it.

I encounter 2 problems:

1. There is a cache issue where the REPL is trying to load an non existing bundle file.

![image](https://user-images.githubusercontent.com/4760796/101201704-760d1680-3668-11eb-8278-164a0fc2e731.png)

Full url: https://fable.io/repl/app.2e87a0d750e00dfae456.js

2. If I force to load without the cache then there an error reported by Thoth.Json when receiving information from/on the worker.

```
[FABLE WORKER] Cannot decode: Error at: `$`
The following `failure` occurred with the decoder: Expected 5 union fields but got 4 worker.min.js:14:163010
```

**Comment by alfonsogarciacaro** [comment]
Oh my, this is weird. I did try after the update and it worked when clearing the cache but I realize now I have to do it **every time** I open the repl in a new tab. Maybe the service worker is not working properly and we should disable it?

![screencast](https://user-images.githubusercontent.com/8275461/101225501-ecdff900-36d4-11eb-8834-4f62e89a597b.gif)

**Comment by alfonsogarciacaro** [comment]
I tried to make the ServiceWorker work (pun unintended) but it was giving the same problem so I disabled it for now. Can you please try again?

**Comment by MangelMaxime** [comment]
Hum at first, it wasn't working for me but after openin it in a Private navigation it works. 🤷‍♂️

However, it you compile an "empty" file you get this error in the console: 

```
Uncaught SyntaxError: class statement requires a name
```

Nothing too problematic but well, we don't like errors don't we 😂.

I also, see that Thoth.Json or more general the libraries have been removed. Any plan on re-adding them or it was just too hacky?

**Comment by alfonsogarciacaro** [comment]
Ah, this is funny, it seems it outputs and empty class for an empty file.

![image](https://user-images.githubusercontent.com/8275461/101256130-9f11d200-3762-11eb-9989-afb0c06dcd8b.png)

About the libraries, yes it was hacks all over the place to make them work. I had an idea to serialize inline expressions so any library could be precompiled and loaded onto the repl. I did the first thing, remove the hacks, but unfortunately didn't have have time to implement the second, that is, the new feature. Now I'm in doubt if I should bring back the hacks or try to make the serialized inline expressions work 🤔

**Comment by MangelMaxime** [comment]
Personnaly, I think that if we can have "clean" solution it is better because in the end upgrading the libraries was not an easy job.
I kind of gave up doing it in the end because of the difficulty. 

It would be interesting to see if we can load libraries from the REPL wihtout bundling them in it. Kind of like some REPL does it for ELM or NPM. They take them from their package manager directly (npm.org or elm package manager). The idea being that, we don't have to release a new version of the REPL for each library and don't increase the chance of breaking the REPL because of that.

But perhaps it is too complex to make such a system...

**Comment by MangelMaxime** [comment]
Ah yes, I didn't look at the generated JavaScript ^^

**Comment by alfonsogarciacaro** [comment]
If what I have in mind can be implemented, it should be po

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro Well, if it's just about sending the code somewhere I think it is still better than the previous REPL which had a strong link between the library and the REPL.

**Comment by alfonsogarciacaro** [comment]
I'll close this as the repl should be working now, please reopen if you still have issues.

**Comment by MangelMaxime** [comment]
Well, there is still the cache problem on first load. But forcing to clean the cache seems to works.

Perhaps, we could show a message on the loading page saying if loading take more that X... please reload clearing your cache... Not great UX neither...

**Comment by alfonsogarciacaro** [comment]
Seems the ServiceWorker was still lingering around 😡 I've made another attempt to remove it, can you please try again? (unfortunately you still may need to hard refresh once)

**Comment by MangelMaxime** [comment]
On this computer it seems ok for me :) Thank you :)
