### ISSUE TITLE
Visiting the site after a while, the site doesn't properly work

### ISSUE THREAD

**Issue by MecuSorin** [fable-compiler/repl#139]
I was navigating to the site using this [link](https://fable.io/repl/#?code=PYBwpgdgBAygngZwC5gLYFgBQpJQGICGARgDZgB0AwsAE5hY7SGkXV3kBSCAkhCjaAbhoAIQEB3BGBpDcY4JOnkAKnHAJZ0AKIlUASwQALLFgD0pqNQAmYKEmBQCVgiCRQOMO2hAkCKBHYOeADEUABmtKh+KFZQyDR6EADmGpiowFYArmRQyt6+KFAAvFhQdmq2XMoESQA8AOTKAHzFUDZkSX62wGFxSDQIAFx9CckA2gC6UABUUGO1AAoENASoAII0K3BNU8spw8BEAFaTUAC0LY2l5eC5NQ3NrXiR0cRkMP2JSeeXyiaYZTIbn6BAgCAiNFQUAAFEgasMqvdGk0AJTDap1ZHFa5lMKZaBhVBuC44spQIEjAJFXJgAAeSHIACUwElssstLSQHQEAg9MAwUyWXToQABABEAG8ADpWADUAF8xSjyDAfHokNDCQznpC-CjSYCwG49lTwkTyABxI0bVmoSBIBDQ-UAsllOFJci8ABuwAA1mBofEEAAaRw0FLOswWAAy6qgRESVi+qXSWRysbcJRdSAqUAAEkhUCQ8qgfF1Wol+GECABjWyQWLmKALXx1wzAEg2GSYa4UwyFkjo-JdTgIDG1AtFktllAtal6Uu0JAAWTQRGkUDF-aQICG5nxIF9HprwFQphI6rO-aLAH5U9kwGLe0a4l6kkPSwUKIi6pPi8PZwrRcaBXNcNy3JAdz3UwDyPcgTzPC8kCvAc7wyB8nxdCk6AgLsYSQYY-2nL8URhMBB3zZRl2jHQ0HtNEoHxON52A0DUHXGhN23XdBn3CBD2PU9z0va8SDQtNH3+JsdH0IwoHEdVDCgDMsHvHIFgEJIVihLNDTcBSkEMDMYT0KxhniL5SOhLlgC01Zhg02ztIaPZQ3qVNyLc1AECSUMM3IIiALAVEHM05z6lcqB3IyTyou83zlPVAKB2Iro5wNckX3I1p5EUGhyAAEVPcgrGAGtMjtPhyCSI1aMqpARDgbgrGhUzIxdV0KSkJAPnLDySDaAwQD8GslN010JopFBPy6ZkEGyTNmzC1ZyC9PQwHEKAbLsqF+sGhBhqQUaMtdfycLw6aZzAOaFqgcj-gmpanJWgzDBgI1esKbrPtsbbtKkixeHVPQCAvAAvWxDMhoK7BqVIm2MqQ0ACewoDoABHTI9DoOxDFsBA31h74ISgCAwGQMBYhgAA1C0vBm-wsD7AcPyulR7gAfTnGkGYoEEwQhKF-NEpmXwJ98ebZ8cudaVKUHIfnwUiRKGXFgH83I8ABiwHNbmUBdbHGsoAB982ATJOJ6KBK1JU3l0STJCitm2OqgU33pPXCoGdvhSTtdiN0MgxyGp0HMkNk6oCiI6lKDgJXsj0283NzjoAuUnE9gMBPdiNOWggTP7YgR3bDzjOe1d-2ONx4PKBIMrfQWaQ6z4GoI9d11NXrvwa4QEOw7AUiLDj8g8GyEhGXN3CHrJKvA8MYOPgEf1sQ72eRtjhf48UzPk4tqAOZ+TcLySfstLASBMMek2oCLkuD6PsVxAXlAr+v93s-5WJD-TsVggABgAEwAGYACcAA2YBmE-ZgU4iPJefowAAHVTKGVXtfKOG9e7yR3mvG+e9OKHztg7QoP8WiAMzh7L+D904AEYZ5lDnnAre5BoyQCSGgo2E1o6jWwQnPBbszb7zIVAQBABWcghcSG2BEcAiRlDP5exEQAFn-pIiuromG91HuPSe+JYhcM0VguOODDK7xTjQlotDAHqIwR-HOD9iHF1IUfcBaj-i61sAVLo+s7SmOMC6LRI81gIAIa0MJI8CHXCCSwkJd9CjUniZDFhSTomwO0SEqhXtqRZNiPAxRVh1ZrBACAHWuZlwxQGtSSgFscJIF8d0Xo3iUANLKbcVcPI26mn1jWX03smk+INv8CkiRgagx+k6dBZIambHtA0qAzSwANPIAAOQUKGSgqArDkAgPyegFcKSZBAM4Qo0Iel9LJvSKyMy6nzI5kgA2pEuE3LmQbUmdIkAbK2TsvZwyXwPLtDQc5+1Dq8K4QpXCChyDdV4PwL0oNNT4ksZHJMB0sFnL0L0hZgy7SrIUM6V0oZaH-xJaRY2LQ9BJF2XQP5bgaz116XmUEsRYQG3RI8qZelMrJE4XYA2rD2FmNdhSUESQcjUhsf-GYt8-CGHIAsbg0qAWsAZY3Zu9o26kj7MygAGq0aEYi1FStlNyjhSlZgngCNCUVOQzgysMvKxVFhJUogJWSbVuEACa+rDXkGNaatBsxeTQGtckW19q5UKqgM6v1rrSTiygAAEjFCmrAtQLxk2uLSWhRQxSGrfnAHNeb-5v1pIAooEpDC6vlNcOA5bK3Ms9TWl08REEVuVSqfoiDm1lFbf6M4CkrCGXbfyhB-oUFDsMPKJoabhJkxaGULAKboGYA9VYZQoB8JstyByrhFIyA8rGny3FbDD1apfHQH0JBHZ8mgNSMI3dgT8tDte-ZnUXw2sNqIv10rlyysddK6El6Ow3v5NG49FAx4kAnlPKwbquVVtwnq6kBqjVQBNQes10rLUwk-ecCNAGY3-zjcKl8iGrDepQ76-1mHA1xESLhsNtg7V-odVGojJHXQJuTamzAtQazY3pW+qANZaQVvIzqntIm4DicbVJmgubAFvzCHoaDI7cVjrANO2dAmaBCYXVAJdvHRZuDWhtGELy+DzOVaRVFoKxqklEkm5daaE1mfECIYAYmxRSqlcSvzJK35kkHcOsUcj-4gFpGKGdLp+OCbIKSUTub82JZk8WoLaNc3KLERllTam-7-xEAAdlAZQLQ0XaimF0-pmeEp6UNyZV7DtISCFSYbbhDdIAIPkBaynZt1w6uqsa3k-lcTpFtfI517rY3nFadq-VxlzLpsIFyRN5lU3msrYKf12L1WEuuyS+l1LyWS2kgU2F3LqmSC5oAcV0r5X41dv9DdoBYDIEZb7WAAdqDDC5todFxdsWqvxeCmSWd4sYsuYro5Ha5BUCN2WlCUZDzxlwkKEck5th3NYHJU9WHr0YCZCIAgGsCRXC3phHiaAIjNnbJ6ITogEGgWYt9M6XHMPtLkFesZMU5FZKGDOC4EAmF2eI-IDQfEQA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8A5AMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3JJAoATgGcCTGmABm5ABwt4wFagwJgAIw5ohkqCl26mAIhSkKUjwodFxI2t5YOMBojJh0aD5IUBB0uiDkfqQR1jEMVkpOLvCIKpCwcEA&css=Q) .
The solution for me was to delete the Cache Storage data for Fable.io

**Comment by MangelMaxime** [comment]
Ok, so this is on https://fable.io/repl/ which we tough to have fixed. 😅

@alfonsogarciacaro Any new ideas? ^^

**Comment by MecuSorin** [comment]
There is no way to invalidate that cache? To timestamp it at the last action in site and if is older than 5 days to just wipe it out?

**Comment by MangelMaxime** [comment]
Well, in theory we should not have the cache system anymore.

It was introduce in this PR https://github.com/fable-compiler/repl/pull/17/files but we removed the `service-worker` in a later version because it was causing problem.

Can you please check if you have a service-worker installed when navigating to https://fable.io/repl/ 

For example, me I don't:

![image](https://user-images.githubusercontent.com/4760796/130197652-5e9c8cfc-6557-4b8e-824b-23f3684e4c41.png)

If you use Firefox here are the instruction on how to find it: https://developer.mozilla.org/en-US/docs/Tools/Application/Service_workers

If you use another browser I found the instruction by searching "see service worker firefox" on google.

**Comment by MecuSorin** [comment]
Found one just in Edge:
```
Scope: https://fable.io/repl/
Registration ID: 15 (unregistered)
Navigation preload enabled: false
Navigation preload header length: 4
Active worker:
Installation Status: ACTIVATED
Running Status: RUNNING
Fetch handler existence: EXISTS
Script: https://fable.io/repl/service-worker.js
Version ID: 41
Renderer process ID: 10784
Renderer thread ID: 2
DevTools agent route ID: 6
Client:
ID: 647c1488-8771-4efa-8a9f-37bd410b566f
URL: https://fable.io/repl/#?code=PYBwpgdgBAygngZwC5gLYFgBQpJQGICGARgDZgB0AwsAE5hY7SGkXV3kBSCAkhCjaAbhoAIQEB3BGBpDcY4JOnkAKnHAJZ0AKIlUASwQALLFgD0pqNQAmYKEmBQCVgiCRQOMO2hAkCKBHYOeADEUABmtKh+KFZQyDR6EADmGpiowFYArmRQyt6+KFAAvFhQdmq2ygRJADwA5MoAfMVQNmRJfrbAYXFINAgAXL0JyQDaALpQAFRQozUACgQ0BKgAgjTLcI2TSylDwEQAVhNQALTNDSaYZWRuAMZ0nVAAFEjVQ1W1DY0AlC9hqCQQzwkWixDIMD6iSSfyGDWKpTKUFuwwCRVyYAAHkhyAAlMBJbJLLSYkB0BAIPTACAIPEErHPAACACIAN4AHSsAGoAL7Mn7kGA+PRIZ4AnEgmhRJA-RE3MBuXZo8KA8gAcQV60JqEgSAQz1l1yRbyS5F4ADdgABrMDPeIIAA0jhoKUNZgsABkRVAiIkrNDUuksjkvW4SkakBUoAAJJCoEh5VA+J7oxL8MIEO62SCxcxQea+LOGYAkGwyTCIlGGOMkD75Toqao1WPxxPJlDNVNJ2hIACyaCI0igzOrSBAg3MmQgICtpruwFQphIItO1fjAH4g9kwMzKwqoHQIGWXkCYzW2wUwH9nmBazHlL2PTo0LqfkMp96uyAe-3UIOaMOo7jgMk7TrO5Dzouy5IKuNabhk267hWmB5jo+hGFA4gioYUChlgW45PMAhJMsqAIkaKJYUghihi8ehWEM8TQteZLACRKxDERbGkfUuxOnUQa3vxqAIEkTqhuQLYJvWHZvvmxE8XUfFQAJGRCSpIlibhIqSeeMlgJ2cpIiit4tPIig0OQAAiC7kFYwB3JkOp8OQSQKs+zlICIcDcFYzz0W6RpIsi+5SEgkJPIJJCtAYIB+HcOHhsFyUhW4KBJpe+IINkYbydxKzkOaehgOIUCsexZFRTFCBxUgCVGSlEmHse6XtmAWU5VAt5XClXEVeQVGGDACoRYUYWjbY5WkVcea8CKegEMuABetjUat+mOEejhQIYt7gOWVY1i0F4Ng8YBPBJa4kFckbgFAWjmrqVQuvug2Ijqf5DtRBjkAAaotmS2OiryGAYUADOuzTRg+Hq8CAmRIB5r6FQD9DIXmqwgCAWC3bYvZqdFSVIqyUD-SQgPg8M0JQDyN1Rr2onkcFAA+liGAQyRgGTFPdFTyRXCiiTegaLQk9zQPDgA6rQpbMjTTqUKgVjkBA1Jo1gKKZCAziFM8mkDAzMIvFFBsE38RNlNKCVQJpmHYUZrOUOznPi1AEAla75wNcTNsE3b1Gk6jLTu+Irs8grSsq2rAv7kVJW+201W1dbRNXVAAAkzJZ1gNT+uaUB3L4FJFMyUSJKc858AQiTSMyjSIjUiTw-cRcICXTcI0hwXmqjRSslFf2o7TQVQIyNpwFrfdhFOLxgOaQwPa+Zz1yPZRz+QbwvTi4ve8zzROxzbk76vUB70n8WGDyK8NzVHONNGt4kA4-cE4P5NgDyACENSmLfEArz-POK8s5ISwH1Ui5BUBWnASsKAQs3Bax1rYOO4gsBnxgagAa2FaLMlvOhQwpwXAgCQughSBUaBTiwEAA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8A5AMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3JJAoATgGcCTGmABm5ABwt4wFagwJgAIw5ohkqCl26mAIhSkKUjwodFxI2t5YOMBojJh0aD5IUBB0uiDkfqQR1jEMVkpOLvCIKpCwcEA&css=BYFwtgNgNAsAUAIwPYBMCeACA3vDeMBmSAdiALQDOAlgF4CmAXBgIwBsADgB4Dc8AvvHgA6MAEMqxMgGMSIccToAnbLnwoqFdhFFomBCHR6q8AdyooQwJswAMNgKS84+DMDpUA5qGt3HxjABWAK4UIFQEaNKydKRMUjEgSk4uohCeklSJYBRxCUn++oZk6op0UmEkcUgQQWDETgJwwhLsQSAqzvjsoijqxB5MQgBMAKylYMn4RKSUtIwsHEadpuaWTKM2XJN4YooeEmTIICBIYNbjDfBAA
Log:
```

**Comment by MangelMaxime** [comment]
Hum, you should delete it because we don't use it anymore.

But then it doesn't explain why the other browsers  broke. Next time, it happens could you please take a look at the console and see what error is reported.

Because we don't know if this is a cache problem or something else then.

**Comment by alfonsogarciacaro** [comment]
@MecuSorin If you didn't visit the repl for a while, it may have happened the service worker was still active in your browser. We removed it some months ago because of these issues. Hopefully the next time we update the repl you won't have the same issue, could you please report if you see it again?

**Comment by alfonsogarciacaro** [comment]
Closing this as we removed the service worker some time ago. Please feel free to reopen if you still have problems. Thanks!
