### ISSUE TITLE
Fable.Core is outdated (TypeScriptTaggedUnion does not work)

### ISSUE THREAD

**Issue by cannorin** [fable-compiler/repl#150]
The fable version is 3.7.0 but `TypeScriptTaggedUnion` does not work, so it seems the REPL is still using an old version of Fable.Core.

**Comment by alfonsogarciacaro** [comment]
Thanks for letting me know @cannorin! It was a while since we didn't update the libraries in the REPL 😅 I just did it, can you please reload and try again?

**Comment by cannorin** [comment]
It is now refusing to load for some reason. Fable version is now shown as:

```
REPL: 3.7.9
Fable: 0.0.0
```

I also deleted the cache but no luck...

**Comment by alfonsogarciacaro** [comment]
Ups, it seems I broke it in the update. Hopefully it's fixed now, can you please try again?
