### ISSUE TITLE
Fable REPL 4 or 3

### ISSUE THREAD

**Issue by ShalokShalom** [fable-compiler/repl#164]
This Twitter [post](https://mobile.twitter.com/FableCompiler/status/1550429007443017729) hosts a broken link to repl4
The description of this repo says its for repl3

What is it?

**Comment by alfonsogarciacaro** [comment]
We hosted the repl for Fable 4 in a separate URL because there were some problems with JS apps at the beginning. Now the problems have been fixed we've "reunited" the repls again so this one represents the latest state of Fable (it may lag a bit sometimes). Sorry for the confusion!

**Comment by ShalokShalom** [comment]
Thanks, I am glad!
