### ISSUE TITLE
Does not work in safari anymore

### ISSUE THREAD

**Issue by JaggerJo** [fable-compiler/repl#172]
<img width="1451" alt="image" src="https://user-images.githubusercontent.com/13090415/204818660-f48b7c88-6584-4765-9545-3ad93d7acb83.png">

Safari version: Version 16.1 (18614.2.9.1.12)

**Comment by JaggerJo** [comment]
> It works in Chrome

**Comment by MangelMaxime** [comment]
The latest version seems to be working for me in Safari, I will close this issue as this is a little old and the new version is just a few seconds old ^^.

Please feel free to open a new issue if needed
