### ISSUE TITLE
Instead of "general" menu we might just use 2 buttons directly

### ISSUE THREAD

**Issue by forki** [fable-compiler/repl#41]
![image](https://user-images.githubusercontent.com/57396/46088338-841f9c80-c1ac-11e8-9f5e-6448b42822ad.png)

maybe just put these two directly in the toolbar?

**Comment by MangelMaxime** [comment]
This is simple for the share button.

For reset, we have 2 things to consider:
1. We need to change the icon because it's using the same for Refresh. We could use a trash maybe
2. We need to ask confirmation to the user. Maybe a mobal? 

PS: So sad, I loved my inline confirmation system :)

**Comment by alfonsogarciacaro** [comment]
I like the inline confirmation dialog too! The share button can be put below the refresh one. The reset link could go into the Options menu. Just an idea :)

**Comment by cartermp** [comment]
It's actually not clear to me what the utility of the Refresh button is. I actually thought it was a reset button that was a no-op up until I saw this issue.

**Comment by MangelMaxime** [comment]
Yes having twice the same icons provide confusions and also I should add a tooltip when hovering the button explaining what it is doing.

**Comment by MangelMaxime** [comment]
Ok, I made all the buttons from general directly accessible when the sidebar is collapse.

I also changed the icon and hopefully it will make things more clear, if it is still not enough we also have tooltip displayed when sidebar is collapse.

![repl_demo](https://user-images.githubusercontent.com/4760796/74575917-20f0fe80-4f89-11ea-8b07-53c4cdcdfc2b.gif)
