### ISSUE TITLE
Add option to format code with Fantomas

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fable-compiler/repl#66]
It's been suggested by @jindraivanek at FableConf to add Fantomas support to the REPL. I think this would be a very nice opt-in (users don't need to use it if they don't need it) and would improve the synergies between projects.

It shouldn't be difficult to add as Fantomas provides an HTTP endpoint for this (@jindraivanek can you confirm the endpoint, whether it supports CORS and the format of the JSON request/response). The main issue as pointed out by @MangelMaxime is when the user modifies the code before we get a response from Fantomas server. Probably the easiest solution to overcome this for now is just to block code edition until we receive a response.

**Comment by jindraivanek** [comment]
endpoint is ratatosk.dynu.net/api/fantomas. I using Fable.Remoting, api interface is here: https://gitlab.com/jindraivanek/fantomas-ui/blob/master/src/Shared/Shared.fs#L66 Thats all I know about it :)

Also there is limitation of source size < 10kB, because of limited resources on server.

**Comment by MangelMaxime** [comment]
Hello @jindraivanek I tried to add support for fantomas in the REPL however the request are rejected by CORS policy.

Is it possible to allow requests coming from `gitpod.io` (used for developping the REPL) and `fable.io` (production website) ?

**Comment by jindraivanek** [comment]
Hello @MangelMaxime,
added `https://gitpod.io`, ` https://fable.io` to CORS for `https://fantomas.azurewebsites.net`.

**Comment by MangelMaxime** [comment]
Awesome @jindraivanek , I will take a look again at this issue :)

**Comment by MangelMaxime** [comment]
I am closing this issue because it is old and I believe the Fantomas service is hosted somewhere else now.
