### ISSUE TITLE
Using plain React in repl

### ISSUE THREAD

**Issue by nojaf** [fable-compiler/repl#69]
Not entirely sure that problem isn't in my own code but I would expect this to work:

```fsharp
module SimpleReact

open Fable.Import
open Fable.Helpers.React

let app =
    div [] [str "👌"]

let element = Browser.document.querySelector "#app"

ReactDom.render(app, element)
```

In the console I see
```
Uncaught TypeError: Failed to resolve module specifier "react-dom". Relative references must start with either "/", "./", or "../".
```

**Comment by MangelMaxime** [comment]
Seems like when we use the `Fable.Import.React` API we have this problem.

For now, you can use `Fable.Helpers.React` API

```fs
// More info about Fulma at https://mangelmaxime.github.io/Fulma/
module Fulma.Content

open Fable.Helpers.React
open Fulma

let app =
    div [] [str "👌"]

app
|> mountById "elmish-app"
```

**Comment by alfonsogarciacaro** [comment]
Hmm, I'll have to add conditional compilation to Fable.Import.React too. But as the way to load the library is not final yet, I'd prefer not to add more `#if FABLE_REPL_LIB` to React bindings. If you don't mind, let's accept the workaround for now and close this issue so we can rethink later a better way to load libraries in the REPL.
