### ISSUE TITLE
A better default font on Windows

### ISSUE THREAD

**Issue by vasily-kirichenko** [fable-compiler/repl#72]
Monaco font is a rare guest on Windows :) So, (the browser? or who?) chooses Courier New, which is very unreadable:

![image](https://user-images.githubusercontent.com/873919/48127373-9ce39d80-e294-11e8-9d87-3417bfc67e0d.png)

I suggest to use Consolas as the default font on Windows, and add more popular options, like SF Mono, Menlo on Mac, and IBM Plex Mono, Input Mono, Hack - on all OSes.

**Comment by MangelMaxime** [comment]
The rule for the browser is `Menlo, Monaco, "Courier New", monospace` when using `Monaco default`.
