### ISSUE TITLE
Warnings when opening console

### ISSUE THREAD

**Issue by forki** [fable-compiler/repl#75]
![image](https://user-images.githubusercontent.com/57396/48673054-c4145780-eb3d-11e8-95c3-24eb50cdd8a8.png)

**Comment by alfonsogarciacaro** [comment]
The one for Thoth.Json happens when the localStorage is empty? Not sure @MangelMaxime 

About the "Cannot find type" ones, I think we talked about it once with @ncave but don't remember if we found the cause. What's `inject.js`? I don't see that one.
