### ISSUE TITLE
Button styles for calculator sample should be moved to CSS page

### ISSUE THREAD

**Issue by forki** [fable-compiler/repl#79]
would be nixe to have.

/cc @Zaid-Ajaj

**Comment by Zaid-Ajaj** [comment]
@MangelMaxime the styles are still implemented in the fsharp file, shouldn't they be removed as well and reference the CSS classes?

**Comment by MangelMaxime** [comment]
Oups, I guess I forgot to port the change to the F# file and only ported the CSS changes 🤷‍♂️

**Comment by MangelMaxime** [comment]
I released a new version with the fix
