### ISSUE TITLE
compile infinite

### ISSUE THREAD

**Issue by fajprieto** [fable-compiler/repl#84]
module Registros = 

    /// Este ejemplo muestra como se define un nuevo registro.  
    type Contacto = 
        { Nombre     : string
          Telefono    : string
          Verificado : bool }
              
    /// Este ejemplo muestra como se instancia un registro.
    let contacto1 = 
        { Nombre = "Alf" 
          Telefono = "(206) 555-0157" 
          Verificado = false }

    /// Se puede colocar todo en la misma linea con el separador ';'.
    let contactoEnLinea = { Nombre = "Alf"; Telefono = "(206) 555-0157"; Verificado = false }

    /// Este ejemplo muestra como usar "copy-and-update" en los valores de un registro. Esto crea 
    /// un nuwvo registro de valores de contacto1, pero tiene diferentes valores para los campos 
    /// 'Telefono' y 'Verificado'.
    ///
    /// Puede aprender mas visitando: https://docs.microsoft.com/dotnet/fsharp/language-reference/copy-and-update-record-expressions
    let contacto2 = 
        { contacto1 with 
            Telefono = "(206) 555-0112"
            Verificado = true }

    /// Este ejemplo muestra como escribir una funcion que procese un registro.
    /// Esto convierte a 'Contacto' en una cadena de caracteres.
    let mostrarContacto (c: Contacto) = 
        c.Nombre + " Telefono: " + c.Telefono + (if not c.Verificado then " (no verificado)" else "")

    printfn "Para contactar a Alf: %s" (mostrarContacto contacto1)

    /// Este es un ejemplo de un registro con un miembro.
    type contactoAlternativo =
        { Nombre     : string
          Telefono    : string
          Domicilio  : string
          Verificado : bool }

        /// Los miembros se pueden implementar como un objeto.
        member this.ImpresionContacto =
            this.Nombre + " Telefono: " + this.Telefono + (if not this.Verificado then " (no verificado)" else "") + this.Domicilio

    let contactoAlternativo = 
        { Nombre = "Alf" 
          Telefono = "(206) 555-0157" 
          Verificado = false 
          Domicilio = "111 Alf Street" }
   
    // Los miembros pueden ser accedidos usando el operador '.' en una instancia.
    printfn "El contacto alternativo de Alf es %s" contacto1Alternativo.ImpresionContacto

**Comment by alfonsogarciacaro** [comment]
Thanks for reporting @fajprieto! The problem seems to be having two members with same name in the same module (type and value `contactoAlternativo`). This should have been "fixed" in https://github.com/fable-compiler/Fable/commit/8c1534e7c2efd4505ed237fef5086930f456deaf by showing a more descriptive error. I will update the REPL :+1:

**Comment by MangelMaxime** [comment]
The REPL has been updated to latest version of Fable
