### ISSUE TITLE
Unable to compile promise {}

### ISSUE THREAD

**Issue by jbeeko** [fable-compiler/repl#85]
The code `let p = promise {return ()}`

Type-checks as below:
<img width="407" alt="image" src="https://user-images.githubusercontent.com/4968704/51872187-66567580-230d-11e9-9258-c2debd9bf081.png">

However it will not compile. Requesting a compile results in the following three issues:
<img width="561" alt="image" src="https://user-images.githubusercontent.com/4968704/51872289-c4835880-230d-11e9-94bb-6a20e6e10611.png">

To reproduce go to `https://fable.io/repl/` clear the f# pane and paste in the code below 
```
module Test
let p = promise {return ()}
```
and click on compile.

Note:

- Occurs in Safari & Chrome on OSX; Edge and Chrome on Windows 10. 
- Still occurs after clearing browser cache or using a private window. 
- REPL Version: 2.0.11

**Comment by alfonsogarciacaro** [comment]
Yeah, sorry. I changed the library and there seems to be an issue with the promise builder :confused: I'll try to fix that. In the meanwhile, please note that the REPL now includes [Fable.SimpleHttp](https://github.com/Zaid-Ajaj/Fable.SimpleHttp) which is compatible with `async` so you don't need the JS promise (if you just want to make an HTTP call).

**Comment by jbeeko** [comment]
Thx for the suggestion but SimpleHttp will not help.  I've been using the REPL to explore JS inter op because you get immediate feedback on the JS generated. However I can fallback on a fable app with splitter instead.

**Comment by alfonsogarciacaro** [comment]
I think I fixed it! :) Please give it a try. You may need to do a hard reload to convince the service worker to download the latest files.

**Comment by jbeeko** [comment]
Yes, compiles now for me.
