### ISSUE TITLE
About information should change if underlying code has changed.

### ISSUE THREAD

**Issue by jbeeko** [fable-compiler/repl#86]
The REPL has an About popup like this:
![image](https://user-images.githubusercontent.com/4968704/52363785-684cc280-29f8-11e9-9650-b1f99594dfc5.png)

This provides the REPL version number. However the version number before and after #85 was address remained the same, 2.0.11. 

To help with issues the About information should reflect the exact code running on the REPL. This way if someone reports and issue it is trivial to determine if they are running older code due to caching somewhere. 

I don't know how that can be done, perhaps by showing commit hashes?

**Comment by MangelMaxime** [comment]
The version displayed is the Fable version.

We should display:

Versions:
- REPL: XXX
- Fable: 2.0.11

Where XXX is the version of the repl and start using a changelog IMO

**Comment by jbeeko** [comment]
Sure, but right not I don't see where you would get a REPL version from. There do not seem to be any releases so hash is all you have.

**Comment by MangelMaxime** [comment]
If we start using a changelog then you will get the release version in it.
