### ISSUE TITLE
Build broken? StackOverflowException on BuildLib (macOS)

### ISSUE THREAD

**Issue by stroborobo** [fable-compiler/repl#88]
Hey Fable team,

I've tried to build this project and I can't get it working somehow:

```
Starting Target: BuildLib (==> CopyModules)
/usr/local/bin/npm run build-lib

> fable-repl@2.0.0 build-lib /Users/bo/src/fable-repl
> fable-splitter -c src/Lib/splitter.config.js

fable-splitter 2.1.8
fable: Compilation started at 7:03:12 PM
fable-compiler 2.3.6
/Users/bo/src/fable-repl/src/Lib> dotnet restore Fable.Repl.Lib.fsproj
  Restore completed in 43.01 ms for /Users/bo/src/fable-repl/src/Lib/Fable.Repl.Lib.fsproj.


Parsing ./src/Lib/Fable.Repl.Lib.fsproj...
child proccess errored: Process is terminating due to StackOverflowException.
```

I'm on a Mac running macOS 10.14.4 and the requested dotnet 2.2.203 of course. On my way I had to change the first line of the build.fsx to use forward slashes (is there a platform independent way to `#r` btw?) and update the fsevents npm dependency as it didn't build with Node 12.

Unfortunately there's no additional stack for the error, so I don't really know where to investigate further. Just the DirectoryNotFoundException from checking the output dir after.

Any ideas?

**Comment by alfonsogarciacaro** [comment]
Yeah, this is known. Unfortunately it seems a problem with the F# compiler and we cannot fix it on ourn end. Related https://github.com/Microsoft/visualfsharp/issues/6636

**Comment by stroborobo** [comment]
Oh alright. Thank you for the info.

**Comment by alfonsogarciacaro** [comment]
Not sure why but this seems to be fixed in latest master after updating dependencies ¯\_(ツ)_/¯

**Comment by stroborobo** [comment]
It does, thanks!
