### ISSUE TITLE
Monaco 'scrolling

### ISSUE THREAD

**Issue by Luiz-Monad** [fable-compiler/repl#94]
Would a top 0 would help it stop scrolling on Firefox. Adding it on monaco-aria-container element.

I'm downloading the code as the #91 said (I didn't find it before). 
Let's see if I can fix it only overriding some CSS.

**Comment by alfonsogarciacaro** [comment]
Thanks for the report @Byte-666. Seems there're some problems with Monaco in Firefox (see #91). Have you tried the proposed fix? Is it working? Would it be possible to send a PR?

**Comment by MangelMaxime** [comment]
A new version of REPL has been published which fix this problem
