### ISSUE TITLE
can we have  a  hot key to rerun the code?

### ISSUE THREAD

**Issue by zzz6519003** [fable-compiler/repl#95]

**Comment by MangelMaxime** [comment]
Hello, with the current version of the REPL is you press `Ctrl + S` or `Cmd + S` it will recompile + run the code.

**Comment by zzz6519003** [comment]
thx, cmd+r would be more obvious

**Comment by MangelMaxime** [comment]
Well `Cmd+R` is already used by the browser to reload the page so I prefer to not override this shortcut which is more used than `Cmd+S` in a browser.

You can also use `alt+enter`. In the past, we had the information shown in the toolbar but seems like we lost it. We should make it visible again.

**Comment by MangelMaxime** [comment]
Perhaps, we can a tooltip when hovering the `Compile` button for a certain period of time

**Comment by zzz6519003** [comment]
Good call!

Convention is a big thing!
