### ISSUE TITLE
Elmish examples do not load

### ISSUE THREAD

**Issue by VitalyBrusentsev** [fable-compiler/repl#99]
The Elmish examples provided with REPL fail to execute (even though the compilation is successful).
The errors in the browser indicate that the relevant Elmish js files are not found:
```
GET https://fable.io/repl/js/repl/lib/Fable.React/Fable.Helpers.React.js net::ERR_ABORTED 404
```

**Comment by alfonsogarciacaro** [comment]
Hmm, they're working for me. Can you please try with a hard reload? I've noticed that the service worker prevents updating the cache with new code in some browsers.

**Comment by VitalyBrusentsev** [comment]
@alfonsogarciacaro a couple of hard reloads helped, thank you.
